version: '2.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - ${PORT:-3000}:3000
      - ${DEBUG_PORT:-9229}:9229
    env_file:
      - ./app/secrets.dev.env
    volumes:
      - ./:/var/www/app
      - /var/www/app/app/node_modules
